# This is a basic workflow that is manually triggered

name: Reel_board workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Running automatic testing on reel_board'
        # Default value if no value is explicitly provided
        default: 'Reel_Board'
        # Input has to be provided for the workflow to run
        required: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: | 
        echo "Hello ${{ github.event.inputs.name }}"
        cd /home/guo/zephyrproject/zephyr
        source zephyr.sh
        git checkout main
        git reset --hard
        twister -p reel_board --device-testing --device-serial /dev/ttyACM0 -T tests/ -j 4
